### ISSUE TITLE
Can not find reports

### ISSUE THREAD

**Issue by singhj** [dionwang88/cs542database#10]
Hi,

I could find your report for project 1 but not for the other projects. From what I see in github, you did the projects and did them well but I can't find the documents. Can you please guide me to documentation for projects 2, 3 and 4?

Thanks

**Comment by 1nfo** [comment]
Sorry, we wrote all the documents into one file README, including p1, p2, p3 and p4.
Should we separate them into 4 different docs?

**Comment by singhj** [comment]
Thanks for the clarification. No need to separate them. We're good.
